// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Raydelis_HilarioAP1_P1.DAL;

#nullable disable

namespace Raydelis_HilarioAP1_P1.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20260302002244_Agrega_CantidadPrecio_Detalle")]
    partial class Agrega_CantidadPrecio_Detalle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Raydelis_HilarioAP1_P1.Models.DetallesEntrada", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdEntrada")
                        .HasColumnType("int");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.HasKey("DetalleId");

                    b.HasIndex("IdEntrada");

                    b.ToTable("DetallesEntrada");
                });

            modelBuilder.Entity("Raydelis_HilarioAP1_P1.Models.EntradasHuacales", b =>
                {
                    b.Property<int>("IdEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEntrada"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEntrada");

                    b.ToTable("EntradasHuacales");
                });

            modelBuilder.Entity("Raydelis_HilarioAP1_P1.Models.TiposHuacales", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Existencia")
                        .HasColumnType("int");

                    b.HasKey("TipoId");

                    b.ToTable("TiposHuacales");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            Descripcion = "Rojo",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 2,
                            Descripcion = "Verde",
                            Existencia = 0
                        });
                });

            modelBuilder.Entity("Raydelis_HilarioAP1_P1.Models.DetallesEntrada", b =>
                {
                    b.HasOne("Raydelis_HilarioAP1_P1.Models.EntradasHuacales", null)
                        .WithMany("DetallesEntrada")
                        .HasForeignKey("IdEntrada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Raydelis_HilarioAP1_P1.Models.EntradasHuacales", b =>
                {
                    b.Navigation("DetallesEntrada");
                });
#pragma warning restore 612, 618
        }
    }
}
